/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\models\level_base.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export const Level_office = (props) => {
  const { nodes, materials } = useGLTF(`${import.meta.env.BASE_URL}models/level_office.glb`);
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.door.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.walls.geometry} material={materials.M_walls} />
      <mesh geometry={nodes.whiteboardbig.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.cabinet.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.cabinet001.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.Chair_Office.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.floor.geometry} material={materials.M_floor} />
      <mesh geometry={nodes.Computer_Keyboard005.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.mouse.geometry} material={materials.M_Atlas} position={[-6.904, 1.997, 11.57]} rotation={[0, 0.288, 0]} />
      <mesh geometry={nodes.projector.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.Chair_B.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.Shelf.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.cardbox.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.separator.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.desk.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.CoffeeTable.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.kitchen_cabinet.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.kitchen_cabinet001.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.kitchen_cabinet002.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.kitchen_cabinet003.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.walltv.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.Table_Box.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.Table_Circular.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.CoffeeMachine.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.pillar.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.Fruit_Apple.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.Fruit_Banana.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.Fruit_Orange.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.Fruit_Plate.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.whiteboardstand.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.Printer.geometry} material={materials.M_Atlas} position={[0, 0, 1.287]} />
      <mesh geometry={nodes.Office_Files.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.CoffeeCup.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.phone.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.Clock.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.Stool.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.monitor.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.cardbox001.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.kettle.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.cabinet002.geometry} material={materials.M_Atlas} position={[0, 0, 1.287]} />
      <mesh geometry={nodes.desk001.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.desk002.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.Computer_Keyboard001.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.Computer_Keyboard002.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.monitor002.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.monitor001.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.monitor003.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.Fruit_Banana001.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.door001.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.Chair_B001.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.Stool001.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.Chair_Office001.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.Chair_Office002.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.Chair_Office003.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.separator001.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.separator002.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.Office_Files001.geometry} material={materials.M_Atlas} position={[0, 0, 1.287]} />
      <mesh geometry={nodes.mouse001.geometry} material={materials.M_Atlas} position={[-10.814, 1.997, 11.57]} rotation={[0, -0.001, 0]} />
      <mesh geometry={nodes.mouse002.geometry} material={materials.M_Atlas} position={[-14.827, 1.997, 11.57]} rotation={[0, -0.001, 0]} />
      <mesh geometry={nodes.entrydoor.geometry} material={materials.M_Atlas} position={[-17.033, 0, 0.07]} />
      <mesh geometry={nodes.desk003.geometry} material={materials.M_Atlas} position={[-13.141, 0, -4.88]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.chairwait.geometry} material={materials.M_Atlas} position={[-8.39, 0, -10.688]} />
      <mesh geometry={nodes.chairwait001.geometry} material={materials.M_Atlas} position={[-6.604, 0, -10.688]} />
      <mesh geometry={nodes.chairwait002.geometry} material={materials.M_Atlas} position={[-2.967, 0, -10.688]} />
      <mesh geometry={nodes.chairwait003.geometry} material={materials.M_Atlas} position={[-1.218, 0, -10.688]} />
      <mesh geometry={nodes.Computer_Keyboard003.geometry} material={materials.M_Atlas} position={[-8.294, 0.006, -16.371]} />
      <mesh geometry={nodes.mouse003.geometry} material={materials.M_Atlas} position={[-15.199, 2.003, -4.801]} rotation={[0, 0.288, 0]} />
      <mesh geometry={nodes.monitor004.geometry} material={materials.M_Atlas} position={[-8.294, 0.006, -16.371]} />
      <mesh geometry={nodes.Chair_Office004.geometry} material={materials.M_Atlas} position={[-14.462, 0.515, -6.588]} rotation={[0, 1.06, 0]} />
      <mesh geometry={nodes.Office_Files002.geometry} material={materials.M_Atlas} position={[-11.78, 2.009, -5.135]} rotation={[-Math.PI, 0.986, -Math.PI]} />
      <mesh geometry={nodes.phone001.geometry} material={materials.M_Atlas} position={[-15.903, 2.111, -4.666]} rotation={[0, -0.248, 0]} />
      <mesh geometry={nodes.Cylinder.geometry} material={materials.M_Atlas} position={[-4.838, 0, -10.706]} scale={0.188} />
      <mesh geometry={nodes.window.geometry} material={materials.M_Atlas} position={[6.964, 3.269, -11.619]} scale={[1, 1, 1.423]} />
    </group>
  );
};

useGLTF.preload(`${import.meta.env.BASE_URL}models/level_office.glb`);
