/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\models\level_base.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export const Level_office = (props) => {
  const { nodes, materials } = useGLTF("/models/level_office.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.door.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.walls.geometry} material={materials.M_Atlas} />
      <mesh
        geometry={nodes.whiteboardbig.geometry}
        material={materials.M_Atlas}
      />
      <mesh geometry={nodes.cabinet.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.cabinet001.geometry} material={materials.M_Atlas} />
      <mesh
        geometry={nodes.Chair_Office.geometry}
        material={materials.M_Atlas}
      />

      <mesh geometry={nodes.floor.geometry} material={materials.M_Atlas} />
      <mesh
        geometry={nodes.Computer_Keyboard005.geometry}
        material={materials.M_Atlas}
      />
      <mesh geometry={nodes.mouse.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.projector.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.Chair_B.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.Shelf.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.cardbox.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.separator.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.desk.geometry} material={materials.M_Atlas} />
      <mesh
        geometry={nodes.CoffeeTable.geometry}
        material={materials.M_Atlas}
      />
      <mesh
        geometry={nodes.kitchen_cabinet.geometry}
        material={materials.M_Atlas}
      />
      <mesh
        geometry={nodes.kitchen_cabinet001.geometry}
        material={materials.M_Atlas}
      />
      <mesh
        geometry={nodes.kitchen_cabinet002.geometry}
        material={materials.M_Atlas}
      />
      <mesh
        geometry={nodes.kitchen_cabinet003.geometry}
        material={materials.M_Atlas}
      />
      <mesh geometry={nodes.walltv.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.Table_Box.geometry} material={materials.M_Atlas} />
      <mesh
        geometry={nodes.Table_Circular.geometry}
        material={materials.M_Atlas}
      />
      <mesh
        geometry={nodes.CoffeeMachine.geometry}
        material={materials.M_Atlas}
      />
      <mesh geometry={nodes.pillar.geometry} material={materials.M_Atlas} />
      <mesh
        geometry={nodes.Fruit_Apple.geometry}
        material={materials.M_Atlas}
      />
      <mesh
        geometry={nodes.Fruit_Banana.geometry}
        material={materials.M_Atlas}
      />
      <mesh
        geometry={nodes.Fruit_Orange.geometry}
        material={materials.M_Atlas}
      />
      <mesh
        geometry={nodes.Fruit_Plate.geometry}
        material={materials.M_Atlas}
      />
      <mesh
        geometry={nodes.whiteboardstand.geometry}
        material={materials.M_Atlas}
      />
      <mesh geometry={nodes.Printer.geometry} material={materials.M_Atlas} />
      <mesh
        geometry={nodes.Office_Files.geometry}
        material={materials.M_Atlas}
      />
      <mesh geometry={nodes.CoffeeCup.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.phone.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.Clock.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.Stool.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.monitor.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.cardbox001.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.kettle.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.cabinet002.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.desk001.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.desk002.geometry} material={materials.M_Atlas} />
      <mesh
        geometry={nodes.Computer_Keyboard001.geometry}
        material={materials.M_Atlas}
      />
      <mesh geometry={nodes.mouse001.geometry} material={materials.M_Atlas} />
      <mesh
        geometry={nodes.Computer_Keyboard002.geometry}
        material={materials.M_Atlas}
      />
      <mesh geometry={nodes.mouse002.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.monitor002.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.monitor001.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.monitor003.geometry} material={materials.M_Atlas} />
      <mesh
        geometry={nodes.Fruit_Banana001.geometry}
        material={materials.M_Atlas}
      />
      <mesh geometry={nodes.door001.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.Chair_B001.geometry} material={materials.M_Atlas} />
      <mesh geometry={nodes.Stool001.geometry} material={materials.M_Atlas} />
      <mesh
        geometry={nodes.Chair_Office001.geometry}
        material={materials.M_Atlas}
      />
      <mesh
        geometry={nodes.Chair_Office002.geometry}
        material={materials.M_Atlas}
      />
      <mesh
        geometry={nodes.Chair_Office003.geometry}
        material={materials.M_Atlas}
      />
      <mesh
        geometry={nodes.separator001.geometry}
        material={materials.M_Atlas}
      />
      <mesh
        geometry={nodes.separator002.geometry}
        material={materials.M_Atlas}
      />
      <mesh
        geometry={nodes.Office_Files001.geometry}
        material={materials.M_Atlas}
      />
    </group>
  );
};

useGLTF.preload("./models/level_office.glb");
