/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\models\capsule.glb 
*/

import React, { forwardRef } from "react";
import { useGLTF } from "@react-three/drei";
import { MeshBasicMaterial } from "three";

export const NesCapsulePlaceholder = forwardRef((props, ref) => {
  const { ...otherProps } = props;
  const { nodes, materials } = useGLTF(
    `${import.meta.env.BASE_URL}models/nesCapsule.glb`
  );
  return (
    <group {...otherProps} dispose={null} ref={ref}>
      <mesh
        geometry={nodes.nesCapsule.geometry}
        material={
          new MeshBasicMaterial({
            color: props.color,
            transparent: true,
            opacity: 0.5,
          })
        }
        transparent
      />
    </group>
  );
});

useGLTF.preload(`${import.meta.env.BASE_URL}models/nesCapsule.glb`);
