/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\models\capsule.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { MeshStandardMaterial } from "three";
import { MeshCollider } from "@react-three/rapier";

export const NesCapsule = (props) => {
  const { nodes, materials } = useGLTF("./models/nesCapsule.glb");
  return (
    <group {...props} dispose={null}>
      <MeshCollider type="hull" >
        <mesh geometry={nodes.UCX_nesCapsule_01.geometry} visible={false}/>
        <mesh geometry={nodes.UCX_nesCapsule_02.geometry} visible={false} />
      </MeshCollider>
      <mesh
        castShadow
        geometry={nodes.nesCapsule.geometry}
        // material={nodes.nesCapsule.material}
        material={new MeshStandardMaterial({ color: props.color })}
      />
    </group>
  );
}

useGLTF.preload("./models/nesCapsule.glb");
